project:
  type: book
  output-dir: docs

lang: ko-KR

book:
  title: "bitPublish를 이용하여 한글 책 조판하기"
  chapters:
    - index.qmd
    - chap_exams.qmd
    - chap_intro_bitpublish.qmd
    - chap_troubleshooting.qmd
    - chap_version.qmd
bibliography: references.bib
link-citations: false
